### ISSUE TITLE
Package qtwebengine5-dev not available for Ubuntu <18.04

### ISSUE THREAD

**Issue by colinmorris** [lvm/build-supercollider#6]
It seems this package [is not available](https://packages.ubuntu.com/search?keywords=qtwebengine5-dev) for versions of Ubuntu earlier than 18.04. It would be great if there were a workaround for this (perhaps I can use an earlier version of Supercollider to avoid this dependency?), but even if not, I think this failure mode could be made more clear. 

In effect, what I saw when I tried to run `build-supercollider.sh` on Ubuntu 16.04 were error messages from the build step like:

```
-- Could NOT find Sndfile (missing:  SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR) 
CMake Error at server/plugins/CMakeLists.txt:135 (message):
  Cannot find libsndfile
```

```
-- Checking for module 'jack'
--   No package 'jack' found
CMake Error at server/scsynth/CMakeLists.txt:21 (message):
  Jack selected as audio API, but development files not found
```

Which turned out to be red herrings. It took me a while to realize what the actual problem was - because it couldn't find the `qtwebengine5-dev` package, the whole `sudo apt install` command aborts, and none of the specified packages get installed (including `libsndfile1-dev` etc., hence the errors above). At this point, I think the whole build script should quit, rather than trying to continue with cloning and building the source. (It did also produce the message `E: Unable to locate package qtwebengine5-dev`, but it was above tons of other output, and took me a while to notice.)

*Edit*: [The SuperCollider install docs](https://github.com/supercollider/supercollider/blob/develop/README_LINUX.md#installing-qt) talk about this issue, and describe a solution that works for 14.04 and 16.04 involving installing from a launchpad PPA.  This workaround also requires modifying the `-DCMAKE_PREFIX_PATH` flag in the build script ([described here](https://github.com/supercollider/supercollider/blob/develop/README_LINUX.md#nonstandard-qt-locations)). Following these steps, I was able to build successfully.

**Comment by lvm** [comment]
I understand your issue but i will not fix this issue since 16.04 is a really old LTS (about 3yr or so). 
I'll only support the latest LTS release for this script (18.04). Also this script will be "deprecated" eventually as I'm working on preparing a .deb package so it's not necessary to compile it (from the user perspective). You can check the gh-pages branch from this repo. 

FWIW, I believe you could apply manually these changes you're mentioning and use this script without any issues (all this script does is update deb repos, run git clone and cmake).

**Comment by colinmorris** [comment]
I mean, it's a long-term support release - it's supported until 2021. Anyways, I'm not saying the script needs to support 16.04, it would just be nice if a) the minimum supported ubuntu version was mentioned in the README b) The script were to fail fast if a required package can't be installed, rather than continuing futilely and generating confusing build errors later down the line.

**Comment by pselle** [comment]
@colinmorris Did you figure out a workaround for this? I'm running Linux Mint 18.2 and ran into the path you described (redherring, trying to figure out how to deal with qtwebengine5, including I used this intense Qt installer but nada, the script still doesn't work and I'd like to get SuperCollider on this machine :disappointed: )

**Comment by pselle** [comment]
Future reader, if you got to this because you figured out that you were unable to locate packages and the installing dependencies step failed, and you followed the SuperCollider instructions on getting Qt on your machine ... to use the handy script in this repo, update this line:

`          -DCMAKE_PREFIX_PATH= \`

to your Qt path (for example:)
`          -DCMAKE_PREFIX_PATH=/opt/qt511 \`

This assumes you edited so that you installed all the other prereqs (deleting the qtwebengine5-dev bit from the install section)

**Comment by lvm** [comment]
Thanks @pselle, will add your comment to the readme just in case anyone else rans into this issue.
